---
apiVersion: v1
kind: Pod
metadata:
  name: dynamic-low-latency-pod
  annotations:
    cpu-quota.crio.io: "disable"
    cpu-load-balancing.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: dynamic-low-latency-pod
      image: "registry.redhat.io/openshift4/cnf-tests-rhel8:v4.16"
      command: ["sleep", "10h"]
      resources:
        requests:
          cpu: 2
          memory: "200M"
        limits:
          cpu: 2
          memory: "200M"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ALL]
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  runtimeClassName: performance-dynamic-low-latency-profile
