---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-ptp
  labels:
    name: openshift-ptp
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ptp-operators
  namespace: openshift-ptp
spec:
  targetNamespaces:
    - openshift-ptp
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ptp-operator-subscription
  namespace: openshift-ptp
spec:
  channel: stable
  name: ptp-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
# ---
# apiVersion: ptp.openshift.io/v1
# kind: PtpConfig
# metadata:
#   name: default
#   namespace: openshift-ptp
# spec:
#   profile:
#     - name: default
#       interface: "ens787f1"
#       ptp4lOpts: "-s -2"
#       phc2sysOpts: "-a -r"
#   recommend:
#     - profile: default
#       priority: 10 10
#       match:
#         - nodeLabel: "node-role.kubernetes.io/worker"
