---
apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: master
spec:
  cpu:
    isolated: 0-1
    reserved: 3-4
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
      - size: "1G"
        count: 16
        node: 0
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: "master"
  name: 99-master-realtime
spec:
  kernelType: realtime
