---
apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: master
spec:
  cpu:
    isolated: 4-16
    reserved: 0,1,2,3
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
      - size: "1G"
        count: 16
        node: 0
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
