---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  manageNodes: false
  network:
    ipFamily: IPv4
  managedResources: {}
  monDataDirHostPath: /var/lib/rook
  multiCloudGateway:
    reconcileStrategy: manage
  resources:
    mgr:
      requests:
        cpu: "1m"
        memory: 1Mi
    mds:
      requests:
        cpu: "1m"
        memory: 1Mi
    mon:
      requests:
        cpu: "1m"
        memory: 1Mi
    osd:
      requests:
        cpu: "1m"
        memory: 1Mi
    rgw:
      requests:
        cpu: "1m"
        memory: 1Mi
    noobaa-core:
      requests:
        cpu: "1m"
        memory: 1Mi
    noobaa-db:
      requests:
        cpu: "1m"
        memory: 1Mi
    noobaa-db-vol:
      requests:
        storage: 50Gi
    noobaa-endpoint:
      requests:
        cpu: "1m"
        memory: 1Mi
  storageDeviceSets:
    - count: 1
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1
          storageClassName: localblock
          volumeMode: Block
      name: ocs-deviceset
      placement: {}
      portable: false
      replica: 3
