---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  annotations: {}
data:
  config.yaml: |
    alertmanagerMain:
      enabled: false
    telemeterClient:
      enabled: false
    prometheusK8s:
      enforcedBodySizeLimit: automatic
      resources:
        limits:
          memory: 1536Mi
        requests:
          memory: 256Mi
      retention: 24h
