---
apiVersion: v1
kind: Namespace
metadata:
  name: vm-workloads
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-ex
  namespace: vm-workloads
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/br-ex
spec:
  config: '{"cniVersion": "0.3.1", "type": "ovs", "bridge": "br-ex"}'
