---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
    vm.kubevirt.io/validations: |
      [
        {
          "name": "minimal-required-memory",
          "path": "jsonpath::.spec.domain.memory.guest",
          "rule": "integer",
          "message": "This VM requires more memory.",
          "min": 2147483648
        }
      ]
  generation: 1
  labels:
    app: ssc600-vm
    kubevirt.io/dynamic-credentials-support: "true"
    vm.kubevirt.io/template: ssc600-vm
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: "1"
  name: ssc600-vm
  namespace: vm-workloads
spec:
  # dataVolumeTemplates:
  #   - metadata:
  #       creationTimestamp:
  #       name: ssc600-vm
  #     spec:
  #       preallocation: false
  #       source:
  #         http:
  #           url: http://alufis35.uv.es/~iranzo/www2/ssc600_disk.img
  #       storage:
  #         resources:
  #           requests:
  #             storage: 40Gi
  #         storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  runStrategy: Always
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: ssc600-vm
        vm.kubevirt.io/workload: server
        k8s.v1.cni.cncf.io/networks: '[{"name":"vm-private-l2-net","namespace":"vm-workloads","ips":["192.168.2.10/24"]}]'
      creationTimestamp:
      labels:
        kubevirt.io/domain: ssc600-vm
        kubevirt.io/size: small
        network.kubevirt.io/headlessService: headless
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 4
          threads: 1
          # dedicatedCpuPlacement: true    # This will require increasing number of CPU's in the hosts
          # isolateEmulatorThread: true
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - bootOrder: 2
              disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: private-l2-interface # <--- UNIQUE NAME for this interface within the VM (MUST MATCH the one used for ssc600-vm)
              bridge: {}
            - macAddress: 02:fe:41:00:00:02
              bridge: {}
              name: br-ex

          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 8Gi
        resources: {}
      evictionStrategy: LiveMigrate
      networks:
      #      - name: default
      #        pod: {}
        - name: private-l2-interface # <--- This name MUST match the new interface name above
          multus:
            networkName: vm-workloads/vm-private-l2-net # <---
        - name: br-ex
          multus:
            networkName: br-ex

      terminationGracePeriodSeconds: 180
      volumes:
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: fedora
              chpasswd:
                expire: false
          name: cloudinitdisk
        - dataVolume:
            name: ssc600-vm-disk
          name: rootdisk
