---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-k8s
  namespace: openshift-monitoring
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-monitoring-operator
  namespace: openshift-monitoring
spec:
  replicas: 0
