---
apiVersion: v1
kind: Namespace
metadata:
  name: vm-workloads
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-ex
  namespace: vm-workloads
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/br-ex
spec:
  config: '{"cniVersion": "0.3.1", "type": "ovs", "bridge": "br-ex"}'
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
    vm.kubevirt.io/validations: |
      [
        {
          "name": "minimal-required-memory",
          "path": "jsonpath::.spec.domain.memory.guest",
          "rule": "integer",
          "message": "This VM requires more memory.",
          "min": 2147483648
        }
      ]
  generation: 1
  labels:
    app: ssc600-vm
    kubevirt.io/dynamic-credentials-support: "true"
    vm.kubevirt.io/template: ssc600-vm
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: "1"
  name: ssc600-vm
  namespace: vm-workloads
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp:
        name: ssc600-vm
      spec:
        preallocation: false
        source:
          http:
            url: http://alufis35.uv.es/~iranzo/www2/ssc600_disk.img
        storage:
          resources:
            requests:
              storage: 40Gi
          storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  runStrategy: Always
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: ssc600-vm
        vm.kubevirt.io/workload: server
      creationTimestamp:
      labels:
        kubevirt.io/domain: ssc600-vm
        kubevirt.io/size: small
        network.kubevirt.io/headlessService: headless
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 4
          threads: 1
          dedicatedCpuPlacement: true
          isolateEmulatorThread: true
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - bootOrder: 2
              disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - macAddress: 02:fe:41:00:00:02
              bridge: {}
              name: br-ex
          #          - macAddress: 02:fe:31:00:00:01
          #            masquerade: {}
          #            model: virtio
          #            name: default
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 8Gi
        resources: {}
      evictionStrategy: LiveMigrate
      networks:
      #      - name: default
      #        pod: {}
        - name: br-ex
          multus:
            networkName: br-ex
      terminationGracePeriodSeconds: 180
      volumes:
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: fedora
              chpasswd:
                expire: false
          name: cloudinitdisk
        - dataVolume:
            name: ssc600-vm
          name: rootdisk
